name: Build binary

on: [push, pull_request]

env:
  ARDUINO_BOARD_MANAGER_ADDITIONAL_URLS: "https://espressif.github.io/arduino-esp32/package_esp32_index.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Install platform
        run:  |
          arduino-cli core update-index
          arduino-cli core install esp32:esp32@3.3.7

      - name: Install dependencies
        run:  |
          arduino-cli lib update-index
          arduino-cli lib install ESPAsyncWebServer


      - name: Compile Sketch for ESP32
        run: cd webserver && arduino-cli compile --output-dir . --fqbn=esp32:esp32:esp32s3:CDCOnBoot=cdc,PSRAM=enabled,PartitionScheme=min_spiffs --warnings=none --verbose webserver.ino

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: webserver.bin
          path: webserver.bin
